seed: 1
model: 'SPACE'
resume: true
resume_ckpt: ''
parallel: false
device_ids: [0, 1]
device: 'cuda:0'
logdir: '../output/logs'
checkpointdir: '../output/checkpoints'
evaldir: '../output/eval/'

dataset: 'CLEVR'
dataset_roots:
  CLEVR: '/home/qsxyh123/Developing/multi_object_datasets'


# For engine.train
train:
  batch_size: 40
  max_epochs: 1000
  max_steps: 320000
  print_every: 200
  save_every: 2000
  num_workers: 4
  clip_norm: 1.0
  max_ckpt: 100
  eval_on: true
  eval_every: 2000
  solver:
    fg:
      optim: 'RMSprop'
      lr: 1e-5
    bg:
      optim: 'Adam'
      lr: 1e-3

# For engine.eval
eval:
  checkpoint: 'best'
  metric: ap_avg

# For package eval
eval_cfg:
  train:
    metrics: ['mse', 'ap']
    num_samples:
      mse: 100
      ap: 100
    batch_size: 40
    num_workers: 4
  test:
    batch_size: 40
    num_workers:
      4

arch:
  G: 8
  fg_sigma: 0.15

  z_pres_start_step: 4000
  z_pres_end_step: 10000
  z_pres_start_value: 0.1
  z_pres_end_value: 0.01

  z_scale_mean_start_step: 10000
  z_scale_mean_end_step: 20000
  z_scale_mean_start_value: -1.0
  z_scale_mean_end_value: -2.0

  tau_start_step: 0
  tau_end_step: 20000
  tau_start_value: 2.5
  tau_end_value: 0.5

  fix_alpha_steps: 0
  fix_alpha_value: 0.1

  K: 5
  bg_sigma: 0.15

  boundary_loss: true
  bl_off_step: 100000

